<?php

declare(strict_types=1);

namespace Ledger\Repositories;

use PDO;

final class UserRepository
{
    public function __construct(private readonly PDO $pdo)
    {
    }

    /** @return array<string, mixed>|null */
    public function findByEmail(string $email): ?array
    {
        $statement = $this->pdo->prepare(
            'SELECT id, name, email, password_hash, status, must_change_password
             FROM users WHERE email = ?'
        );
        $statement->execute([mb_strtolower($email)]);

        return $statement->fetch() ?: null;
    }

    /** @return array<string, mixed>|null */
    public function findActiveById(int $id): ?array
    {
        $statement = $this->pdo->prepare(
            "SELECT id, name, email, must_change_password
             FROM users WHERE id = ? AND status = 'active'"
        );
        $statement->execute([$id]);

        return $statement->fetch() ?: null;
    }

    public function create(string $name, string $email, string $password): int
    {
        return $this->insert($name, $email, $password, mustChangePassword: false);
    }

    /**
     * The admin-provisioned path: the password was generated by us and shown once, so the
     * account is flagged until the holder replaces it with one only they know.
     */
    public function createWithTemporaryPassword(string $name, string $email, string $password): int
    {
        return $this->insert($name, $email, $password, mustChangePassword: true);
    }

    private function insert(string $name, string $email, string $password, bool $mustChangePassword): int
    {
        $this->pdo
            ->prepare(
                'INSERT INTO users (name, email, password_hash, must_change_password)
                 VALUES (?, ?, ?, ?)'
            )
            ->execute([
                $name,
                mb_strtolower($email),
                password_hash($password, PASSWORD_ARGON2ID),
                $mustChangePassword ? 1 : 0,
            ]);

        return (int) $this->pdo->lastInsertId();
    }

    public function updateName(int $id, string $name): void
    {
        $this->pdo->prepare('UPDATE users SET name = ? WHERE id = ?')->execute([$name, $id]);
    }

    public function updatePasswordHash(int $id, string $hash, bool $mustChange): void
    {
        $this->pdo
            ->prepare('UPDATE users SET password_hash = ?, must_change_password = ? WHERE id = ?')
            ->execute([$hash, $mustChange ? 1 : 0, $id]);
    }

    /**
     * Written at most once every five minutes per user. "Last active" on the members
     * screen is not worth a row update on every single request.
     */
    public function touchLastSeen(int $id): void
    {
        $this->pdo
            ->prepare(
                'UPDATE users SET last_seen_at = NOW()
                 WHERE id = ? AND (last_seen_at IS NULL OR last_seen_at < NOW() - INTERVAL 5 MINUTE)'
            )
            ->execute([$id]);
    }
}
